Update fladle options
runningcode/fladle pull request #211
Opened 2021-01-18 20:46 UTC by pawelpasterz

Update fladle with newly added options in flank:
* `grant-permissions`
* `type`
* `scenario-labels`
* `scenario-numbers`
* `obb-files`
* `obb-names`
* `test-targets-for-shard`
* `fail-fast`

2021-01-18 20:50 UTC, pawelpasterz commented
Hey @runningcode, please, take a look.
Thanks!

2021-01-18 22:36 UTC, runningcode requested changes
Hey, thanks for submitting this and the wonderful docs and tests. I copied your docs in to master for `testTargetsForShard`, however I missed the `testTargetsForShard` in the sample configuation.
Please rebase and I'll merge this in.

2021-01-18 22:36 UTC, runningcode approved these changes
Oops, meant to approve.

2021-01-19 05:04 UTC, pawelpasterz commented
I've updated my branch with the latest master changes :)

2021-01-19 09:59 UTC, runningcode commented on docs/configuration.md
> +    testTargetsForShard = [
nice, thanks for adding this. however, i think it is missing in the kotlin sample.

2021-01-19 10:14 UTC, runningcode commented
I really appreciate this. I'm going to merge this in. If you get the chance could you also add the kotlin sample configuration and add this to the release notes under unreleased?

2021-01-19 10:14 UTC, merged

2021-01-19 10:34 UTC, runningcode commented on docs/configuration.md
> +    testTargetsForShard = [
Ignore this comment, the sample configuration has only a groovy version.